import Head from "next/head"
import { GetStaticProps } from "next"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="font-extrabold bg-fuchsia-300">Hello World.</div>
    </div>
  )
}

// TODO: Should we add specific namespaces?
// https://next-intl-docs.vercel.app/docs/usage/messages
export const getStaticProps: GetStaticProps = async (context) => {
  const locale = context.locale

  return {
    props: {
      messages: (await import(`../../i18n/${locale}.json`)).default,
    },
  }
}
